# set ctrl space as prefix
unbind C-b # unbind the default
set -g prefix C-Space # make ctrl space the new prefix
bind C-Space send-prefix # makes sure that nested tmux instance will receive the ctrl space 

set -g mouse on # mouse enabled

# start windows and panes at index 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on # when windows close the indexes are shifted to fill gaps 

# use vim bindings to move between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


# =========== Appearance
# don't do anything when a 'bell' rings
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# clock mode
setw -g clock-mode-colour purple

# copy mode
setw -g mode-style 'fg=black bg=purple bold'

# panes
set -g pane-border-style 'fg=purple'
set -g pane-active-border-style 'fg=green'

# statusbar
set -g status-position bottom
set -g status-justify left
set -g status-style 'fg=purple bg=black'

# # session name
set -g status-left ''
set -g status-right-length 0

# windows
setw -g window-status-current-style 'fg=black bg=purple'
setw -g window-status-current-format ' #I #W #F '
setw -g window-status-style 'fg=purple bg=black'
setw -g window-status-format ' #I #[fg=white]#W #[fg=yellow]#F '
setw -g window-status-bell-style 'fg=green bg=purple bold'

# session name
set -g status-right-style 'fg=black bg=green'
set -g status-right ' #S '
set -g status-right-length 50

# messages
set -g message-style 'fg=green bg=purple bold'
